BEGIN TRANSACTION;
INSERT INTO ministries(name,type,state,parent_ministry) VALUES('Ministry of Statistics & Programme Implementation (MoSPI)','central',NULL,NULL);
INSERT INTO ministries(name,type,state,parent_ministry) SELECT 'Survey Methodology & Sampling','central',NULL,id FROM ministries WHERE name='Ministry of Statistics & Programme Implementation (MoSPI)' AND parent_ministry IS NULL;
INSERT INTO ministries(name,type,state,parent_ministry) SELECT 'National Accounts & Economic Statistics','central',NULL,id FROM ministries WHERE name='Ministry of Statistics & Programme Implementation (MoSPI)' AND parent_ministry IS NULL;
INSERT INTO ministries(name,type,state,parent_ministry) SELECT 'Price & Index Statistics','central',NULL,id FROM ministries WHERE name='Ministry of Statistics & Programme Implementation (MoSPI)' AND parent_ministry IS NULL;
INSERT INTO ministries(name,type,state,parent_ministry) SELECT 'Industrial Statistics','central',NULL,id FROM ministries WHERE name='Ministry of Statistics & Programme Implementation (MoSPI)' AND parent_ministry IS NULL;
INSERT INTO ministries(name,type,state,parent_ministry) SELECT 'SDG, Metadata & Data Quality','central',NULL,id FROM ministries WHERE name='Ministry of Statistics & Programme Implementation (MoSPI)' AND parent_ministry IS NULL;
INSERT INTO ministries(name,type,state,parent_ministry) SELECT 'Data Informatics, AI & Analytics','central',NULL,id FROM ministries WHERE name='Ministry of Statistics & Programme Implementation (MoSPI)' AND parent_ministry IS NULL;
INSERT INTO ministries(name,type,state,parent_ministry) VALUES('Ministry of Agriculture & Farmers Welfare (ES&E / DES)','central',NULL,NULL);
INSERT INTO ministries(name,type,state,parent_ministry) SELECT 'Agricultural Statistics','central',NULL,id FROM ministries WHERE name='Ministry of Agriculture & Farmers Welfare (ES&E / DES)' AND parent_ministry IS NULL;
INSERT INTO ministries(name,type,state,parent_ministry) SELECT 'Cost of Cultivation','central',NULL,id FROM ministries WHERE name='Ministry of Agriculture & Farmers Welfare (ES&E / DES)' AND parent_ministry IS NULL;
INSERT INTO ministries(name,type,state,parent_ministry) SELECT 'Land Use, GIS & Geospatial Analytics','central',NULL,id FROM ministries WHERE name='Ministry of Agriculture & Farmers Welfare (ES&E / DES)' AND parent_ministry IS NULL;
INSERT INTO ministries(name,type,state,parent_ministry) SELECT 'Agricultural Prices & Market Intelligence','central',NULL,id FROM ministries WHERE name='Ministry of Agriculture & Farmers Welfare (ES&E / DES)' AND parent_ministry IS NULL;
INSERT INTO ministries(name,type,state,parent_ministry) VALUES('Ministry of Labour & Employment (Labour Bureau)','central',NULL,NULL);
INSERT INTO ministries(name,type,state,parent_ministry) SELECT 'Labour & Employment Statistics','central',NULL,id FROM ministries WHERE name='Ministry of Labour & Employment (Labour Bureau)' AND parent_ministry IS NULL;
INSERT INTO ministries(name,type,state,parent_ministry) SELECT 'Price & Index Statistics','central',NULL,id FROM ministries WHERE name='Ministry of Labour & Employment (Labour Bureau)' AND parent_ministry IS NULL;
INSERT INTO ministries(name,type,state,parent_ministry) SELECT 'Labour Surveys, Research & Analytics','central',NULL,id FROM ministries WHERE name='Ministry of Labour & Employment (Labour Bureau)' AND parent_ministry IS NULL;
INSERT INTO ministries(name,type,state,parent_ministry) SELECT 'Training, Data Quality & Digitization','central',NULL,id FROM ministries WHERE name='Ministry of Labour & Employment (Labour Bureau)' AND parent_ministry IS NULL;
INSERT INTO ministries(name,type,state,parent_ministry) VALUES('Ministry of Commerce & Industry (Department of Commerce / DGCI&S)','central',NULL,NULL);
INSERT INTO ministries(name,type,state,parent_ministry) SELECT 'Trade Statistics','central',NULL,id FROM ministries WHERE name='Ministry of Commerce & Industry (Department of Commerce / DGCI&S)' AND parent_ministry IS NULL;
INSERT INTO ministries(name,type,state,parent_ministry) SELECT 'Export-Import Data & Commercial Intelligence','central',NULL,id FROM ministries WHERE name='Ministry of Commerce & Industry (Department of Commerce / DGCI&S)' AND parent_ministry IS NULL;
INSERT INTO ministries(name,type,state,parent_ministry) SELECT 'Open Data, APIs & Data Processing','central',NULL,id FROM ministries WHERE name='Ministry of Commerce & Industry (Department of Commerce / DGCI&S)' AND parent_ministry IS NULL;
COMMIT;
